name: PMD Verification

permissions:
  contents: read
  pull-requests: write

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
      - reopened

jobs:
  pmd_validation:
    uses: akohan91/libak-salesforce-ci/.github/workflows/pmd_validation.yaml@main
    secrets: inherit
    with:
      analyze-modified-files-only: false
      create-github-annotations: false
